/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
	const group = useRef()
	const { nodes, materials, animations } = useGLTF('/model.glb')
	//const { actions } = useAnimations(animations, group)
	return (
		<group ref={group} {...props} dispose={null}>
		<group name="Scene">
		<PerspectiveCamera
		name="Camera"
		makeDefault={true}
		far={1000}
		near={1}
		fov={30}
		position={[0, 1, 6]}
		/>
		<mesh
		name="Body"
		castShadow
		receiveShadow
		geometry={nodes.Body.geometry}
		material={materials.Dress}
		position={[0, 0, 0]}>
		<mesh
		name="Arm"
		castShadow
		receiveShadow
		geometry={nodes.Arm.geometry}
		material={materials.Skin}
		/>
		<mesh
		name="Cheekmarks"
		castShadow
		receiveShadow
		geometry={nodes.Cheekmarks.geometry}
		material={materials.Cheeks}
		position={[0.381, 0.345, 0.503]}
		rotation={[Math.PI / 2, 0, 0]}
		scale={0.067}
		/>
		<mesh
		name="Collar"
		castShadow
		receiveShadow
		geometry={nodes.Collar.geometry}
		material={materials.Collar}
		/>
		<mesh
		name="Cross"
		castShadow
		receiveShadow
		geometry={nodes.Cross.geometry}
		material={materials.Cross}
		position={[0, -0.161, 0.25]}
		rotation={[Math.PI / 2, 0, 0]}
		scale={0.032}
		/>
		<mesh
		name="Eye"
		castShadow
		receiveShadow
		geometry={nodes.Eye.geometry}
		material={materials['Eyes and mouth']}
		/>
		<mesh
		name="Eyebrows"
		castShadow
		receiveShadow
		geometry={nodes.Eyebrows.geometry}
		material={materials['Eyes and mouth.001']}
		position={[0.267, 0.643, 0.472]}
		rotation={[-0.126, 0.447, 0.286]}
		scale={[0.732, 0.374, 0.584]}
		/>
		<mesh
		name="Glass"
		castShadow
		receiveShadow
		geometry={nodes.Glass.geometry}
		material={materials.Glass}
		position={[0.259, 0.494, 0.504]}
		rotation={[1.714, -0.065, -0.42]}
		scale={[0.118, 0.109, 0.089]}
		/>
		<mesh
		name="Glasses_center"
		castShadow
		receiveShadow
		geometry={nodes.Glasses_center.geometry}
		material={materials.Glasses}
		position={[0, 0.489, 0.553]}
		/>
		<mesh
		name="Glasses_mount"
		castShadow
		receiveShadow
		geometry={nodes.Glasses_mount.geometry}
		material={materials.Glasses}
		/>
		<mesh
		name="Hair"
		castShadow
		receiveShadow
		geometry={nodes.Hair.geometry}
		material={materials.Hair}
		position={[0, 0.716, 0]}
		/>
		<mesh
		name="Hairpin"
		castShadow
		receiveShadow
		geometry={nodes.Hairpin.geometry}
		material={materials.Hairpin}
		position={[-0.596, 0.542, 0.142]}
		rotation={[0.048, -0.741, 0.211]}
		/>
		<mesh
		name="Head"
		castShadow
		receiveShadow
		geometry={nodes.Head.geometry}
		material={materials.Skin}
		position={[0, 0.716, 0]}
		/>
		<mesh
		name="Leg"
		castShadow
		receiveShadow
		geometry={nodes.Leg.geometry}
		material={materials.Lace}
		/>
		<mesh
		name="Mouth"
		castShadow
		receiveShadow
		geometry={nodes.Mouth.geometry}
		material={materials['Eyes and mouth']}
		/>
		<mesh
		name="Neck"
		castShadow
		receiveShadow
		geometry={nodes.Neck.geometry}
		material={materials.Skin}
		/>
		<mesh
		name="Nose"
		castShadow
		receiveShadow
		geometry={nodes.Nose.geometry}
		material={materials.Skin}
		position={[0, 0.013, 0]}
		/>
		<mesh
		name="Shirt_center"
		castShadow
		receiveShadow
		geometry={nodes.Shirt_center.geometry}
		material={materials.Shirt}
		position={[-0.018, 0.093, 0.246]}
		rotation={[0.058, -0.311, 0.229]}
		scale={1.067}
		/>
		<mesh
		name="Shirt_sides"
		castShadow
		receiveShadow
		geometry={nodes.Shirt_sides.geometry}
		material={materials.Shirt}
		position={[0.072, 0.108, 0.237]}
		rotation={[0.029, 0.118, 0.635]}
		/>
		<mesh
		name="Shoes"
		castShadow
		receiveShadow
		geometry={nodes.Shoes.geometry}
		material={materials.Shoes}
		position={[0.104, -1.054, 0]}
		/>
		<mesh
		name="Shoulder"
		castShadow
		receiveShadow
		geometry={nodes.Shoulder.geometry}
		material={materials.Shirt}
		position={[0.262, 0.022, -0.059]}
		scale={[1.529, 1.431, 1.806]}
		/>
		</mesh>
		</group>
		</group>
	)
}

useGLTF.preload('/test.glb')
